### PR TITLE
Fixes #58: configure Fail2ban sshd port, if enabled

### LINKED ISSUE #58: Configure Fail2ban sshd port, if enabled
This role gives the possibility (and encourages) to change SSH port number.

If the SSH port number is customized (not 22), the `sshd` Fail2ban jail will not work without providing the ssh port to block through a `/etc/fail2ban/jail.local` file.

I will submit a PR to fix this and provide a way to customize jails as well.

### PR DESCRIPTION
**Pull request by f-lopes**
Enhance / fix Fail2ban configuration (ssh port)
- Configure sshd jail port through `jail.local` file
- Add possibility to override `jail.local` fail2ban configuration file

### CODE REVIEW

**Comment by f-lopes** [comment]
Build is failing: https://travis-ci.org/github/f-lopes/ansible-role-security

Tried to debug it using:
```
docker run --rm -it \
    -v "$(pwd)":/tmp/$(basename "${PWD}"):ro -e MOLECULE_DISTRO=centos8 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -w /tmp/$(basename "${PWD}") \
    quay.io/ansible/molecule:3.0.0 \
    molecule --debug test
```

I did not have more logs than that:

```
DEBUG: COMMAND
/usr/bin/ansible-playbook --skip-tags=molecule-notest,notest,molecule-idempotence-notest --diff --inventory=/root/.cache/molecule/ansible-role-security/default/inventory /tmp/ansible-role-security/molecule/default/converge.yml -vvv

ERROR: Idempotence test failed because of the following tasks:
* [instance] => ansible-role-security : Ensure fail2ban is running and enabled on boot.
An error occurred during the test sequence action: 'idempotence'. Cleaning up.
```

**Comment by f-lopes** [comment]
Tested again with --destroy=never: the `fail2ban` service fails to start because of this error:
```
Found no accessible config files for 'filter.d/sshd-ddos' under /etc/fail2ban
```
I will remove the `sshd-ddos` default filter from the default `jail.local` file to ensure CentOS support.

**Comment by f-lopes** [comment]
Build is OK: https://travis-ci.org/github/geerlingguy/ansible-role-security/builds/687900600

**Comment by fama** [comment]
I ran into the same problem.  Changing the ssh port lock you out.  The worse thing is that you don't notice right away until rebooting of the server.  Spent hours trying to debug the lockout problem.  I hope this will be merged soon.
Great work.

**Comment by f-lopes** [comment]
Sorry for the time spent on this problem. I hope it will too! 

Thank you :)

**Comment by geerlingguy** [comment]
Merged, but rearranged the deck chairs a bit in follow-up commit. Thanks for finding and fixing this bug!

**Comment by Rodri9o** [comment]
@f-lopes great find. I learned a few things in the process. Who says reading merged code /comments is a boring activity ;) 
Thanks for the descriptive messages - great way to learn.

**Comment by f-lopes** [comment]
Thanks for merging it!
@Rodri9o Thanks for your message, glad to hear that :)

**Pull request merged**
