### PR TITLE
Switch to ubuntu-upstart base image

### PR DESCRIPTION
**Pull request by oxyc**
Let's see what happens #11

### CODE REVIEW

**Comment by geerlingguy** [comment]
++ fingers crossed!

**Comment by oxyc** [comment]
Compare the service output for [CentOS](https://travis-ci.org/geerlingguy/ansible-role-security/jobs/108599400#L899) with [Ubuntu 12.04](https://travis-ci.org/geerlingguy/ansible-role-security/jobs/108599403#L727), [Ubuntu 14.04](https://travis-ci.org/geerlingguy/ansible-role-security/jobs/108599402#L682) and [phusion/baseimage](https://travis-ci.org/geerlingguy/ansible-role-security/jobs/108599404#L546).

Phusion gives this
> sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm service fail2ban start
 * Starting authentication failure monitor fail2ban       ERROR  Failed during configuration: Have not found any log file for ssh jail

**Comment by geerlingguy** [comment]
Hmm... maybe the installation never creates the log file on 14.04?? "Have not found any log file for ssh jail"

**Comment by geerlingguy** [comment]
http://serverfault.com/a/664185/15673 — maybe we need to make sure SSH is installed _and started_ and a log file exists?

**Comment by oxyc** [comment]
The upstart base image should have SSH enabled already. https://github.com/tianon/dockerfiles/blob/master/sbin-init/ubuntu/upstart/14.04/Dockerfile#L7

But phusion/baseimage seem to be doing pretty well (I tried enabling SSH) so far it seems. If I recall you also had a task about dropping support for Ubuntu 12.04 on Drupal VM?

**Comment by geerlingguy** [comment]
I would like to soon... but not until it hits end of life (April 2017) or maybe slightly sooner, depending on the level of pain it presents.

**Comment by geerlingguy** [comment]
@oxyc - See https://discourse.osmc.tv/t/fail2ban-installation-problem/7196/5 - but this shouldn't be the case on 14.04 if it's using upstart, right? Ugh, you're probably deeper into this right now than I can be, I have a meeting I have to prep for :)

**Comment by oxyc** [comment]
@geerlingguy yes but `auth.log` actually didnt exist on Ubuntu 14.04 for whatever... This is just so confusing...

**Comment by oxyc** [comment]
I got a pass on `phusion/baseimage`! https://travis-ci.org/geerlingguy/ansible-role-security/jobs/108607797

**Comment by geerlingguy** [comment]
Haha, love the commit message. I wonder if it's something that takes a while to start or some weird time delay happening??

**Comment by oxyc** [comment]
So summary:

- `centos-6` and `centos-7` work fine.
- `ubuntu-12.04` works fine.
- `ubuntu-14.04` doesn't start the fail2ban daemon. Fails on 3rd provision too.
- `ubuntu-upstart-12.04` works fine.
- `ubuntu-upstart-14.04` doesn't start the fail2ban daemon. **Passes on 3rd provision!**
- `phusion/baseimage` (Ubuntu 14.04) works fine.

_I've been pulling down different images regardless of the Dockerfile name so on travis look at: `Step 0 : FROM ubuntu-upstart:14.04`_

I'm probably more confused than when I started.

@geerlingguy maybe some timing/delay thingy yeah, but that's an aweful long delay as it needs 3 provisions, not even the idempotence test fixes it.

**Comment by geerlingguy** [comment]
So if `phusion/baseimage` for 14.04 works fine, I'd like to go with that, and we can drop the current `ubuntu-14.04` base image. I'd rather not try to debug these kinds of issues (which I never encounter in real-world usage on non-Dockerized servers) and go with something that's working for now :)

**Pull request merged**
