### PR TITLE
Add Handler for reload of fail2ban.service and add notify to template task of jail.local

### LINKED ISSUE #95: `fail2ban.service` not reloaded after `jail.local` update
When the https://github.com/geerlingguy/ansible-role-security/blob/d7272e427c085543ec6d39541b6cc28e243425e1/defaults/main.yml#L28 is changed / updated the fail2ban.service is not getting reloaded.

This can cause unexpected bans.
If, for example, you configure ignoreip in the override and then after the deployment test it out and get banned.
This totally did not happen to me ;)

PR incoming

### PR DESCRIPTION
**Pull request by BrutalBirdie**
Not much to write here :) This fixes #95 

Cheers 🍻

### CODE REVIEW

**Review by diogopms — APPROVED** [review]
👍🏻

**Comment by nspaeth** [comment]
This also isn't stale, as per https://github.com/geerlingguy/ansible-role-security/issues/95#issuecomment-1251894804

**Comment by Keridos** [comment]
still not stale

**Comment by BrutalBirdie** [comment]
nooooooot staaaalllleeee

**Comment by nspaeth** [comment]
@geerlingguy I am sure you are busy, but I wonder if there are any others who have commit access that can merge this PR?

**Pull request merged**
