### PR TITLE
Fixes unattended upgrades for Debian Buster, and possibly earlier...

### PR DESCRIPTION
**Pull request by tstec-polypoly**
Only tested on Buster.

### CODE REVIEW

**Comment by Ramblurr** [comment]
Yup, this is definitely needed.

**Comment by Ramblurr** [comment]
Bump.

(not sure if you want these sorts of keep-alive posts Jeff, your blog post doesn't mention it, but if you don't want them just let us know)

**Comment by frunika** [comment]
probably not needed for Ubuntu. Maybe even incompatible?

**Comment by Ramblurr** [comment]
Bump.

(not sure if you want these sorts of keep-alive posts Jeff, your blog post doesn't mention it, but if you don't want them just let us know)

**Pull request closed without merging**
